const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.sliderbar,
		C3.Plugins.TextBox,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Button,
		C3.Plugins.PlatformInfo,
		C3.Plugins.SVGPicture,
		C3.Plugins.List,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Clipboard,
		C3.Plugins.BinaryData,
		C3.Plugins.Date,
		C3.Plugins.FileSystem,
		C3.Plugins.Touch,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.sliderbar.Cnds.CompareInstanceVar,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.ResetPoly,
		C3.Plugins.DrawingCanvas.Acts.FillEllipse,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.DrawingCanvas.Exps.BBoxTop,
		C3.Plugins.DrawingCanvas.Acts.AddPolyPoint,
		C3.Plugins.DrawingCanvas.Acts.Line,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.DrawingCanvas.Acts.FillPoly,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.EventSheet1_Event65_Act3,
		C3.JavaScriptInEvents.EventSheet1_Event65_Act5,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.FileSystem.Acts.AddAcceptType,
		C3.Plugins.FileSystem.Acts.ShowOpenFilePicker,
		C3.Plugins.FileSystem.Cnds.OnPickerComplete,
		C3.Plugins.FileSystem.Acts.ReadTextFile,
		C3.Plugins.System.Exps.len,
		C3.Plugins.FileSystem.Exps.FileText,
		C3.Plugins.Browser.Acts.Reload,
		C3.JavaScriptInEvents.EventSheet1_Event73_Act1,
		C3.Plugins.FileSystem.Acts.ShowSaveFilePicker,
		C3.Plugins.FileSystem.Acts.WriteTextFile,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.JavaScriptInEvents.EventSheet1_Event78_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event81_Act1,
		C3.Plugins.List.Acts.Remove,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.Dictionary.Acts.DeleteKey,
		C3.JavaScriptInEvents.EventSheet1_Event84_Act1,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.SVGPicture.Acts.SetImage,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.sliderbar.Cnds.OnChanged,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.JavaScriptInEvents.EventSheet1_Event124_Act2,
		C3.Plugins.System.Exps.rgba255
	];
};
self.C3_JsPropNameTable = [
	{raceBg: 0},
	{cardOverlay: 0},
	{Text: 0},
	{type: 0},
	{statSlider: 0},
	{usernameInput: 0},
	{username: 0},
	{Browser: 0},
	{stats: 0},
	{Keyboard: 0},
	{DrawingCanvas: 0},
	{savePng: 0},
	{value: 0},
	{statMarker: 0},
	{PlatformInfo: 0},
	{Sprite: 0},
	{statTitle: 0},
	{cardRaceIcon: 0},
	{racePickIcon: 0},
	{race: 0},
	{racePickButton: 0},
	{List: 0},
	{Dictionary: 0},
	{addPlayer: 0},
	{LocalStorage: 0},
	{importData: 0},
	{exportData: 0},
	{resetData: 0},
	{Clipboard: 0},
	{imageToClipboard: 0},
	{BinaryData: 0},
	{Date: 0},
	{FileSystem: 0},
	{Touch: 0},
	{removePlayer: 0},
	{credit: 0},
	{player: 0},
	{adaptability: 0},
	{greed: 0},
	{agression: 0},
	{survival: 0},
	{turtle: 0},
	{variety: 0},
	{fillColor: 0},
	{fillColor2: 0},
	{lineSize: 0},
	{pointSize: 0},
	{data: 0},
	{adap: 0},
	{gr: 0},
	{agr: 0},
	{turt: 0},
	{variet: 0},
	{surv: 0},
	{racee: 0},
	{name: 0},
	{ad: 0},
	{ag: 0},
	{tu: 0},
	{va: 0},
	{su: 0},
	{playa: 0},
	{lastX: 0},
	{lastY: 0},
	{firstX: 0},
	{firstY: 0},
	{dx: 0},
	{doTheThing: 0},
	{exists: 0},
	{imageUrl: 0},
	{raceColor2Opacity: 0}
];

self.InstanceType = {
	raceBg: class extends self.ISpriteInstance {},
	cardOverlay: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	statSlider: class extends self.ISliderBarInstance {},
	usernameInput: class extends self.ITextInputInstance {},
	username: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	stats: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	savePng: class extends self.IButtonInstance {},
	statMarker: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	statTitle: class extends self.ITextInstance {},
	cardRaceIcon: class extends self.ISVGPictureInstance {},
	racePickIcon: class extends self.ISVGPictureInstance {},
	racePickButton: class extends self.ISpriteInstance {},
	List: class extends self.IListInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	addPlayer: class extends self.IButtonInstance {},
	LocalStorage: class extends self.IInstance {},
	importData: class extends self.IButtonInstance {},
	exportData: class extends self.IButtonInstance {},
	resetData: class extends self.IButtonInstance {},
	Clipboard: class extends self.IInstance {},
	imageToClipboard: class extends self.IButtonInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Date: class extends self.IInstance {},
	FileSystem: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	removePlayer: class extends self.IButtonInstance {},
	credit: class extends self.ITextInstance {}
}